// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku

// #define MIRYOKU_KLUDGE_TAPDELAY
#define MIRYOKU_LAYER_BASE MIRYOKU_ALTERNATIVES_BASE_QWERTY
#define MIRYOKU_ALPHAS_QWERTY
#define U_REQUIRE_PRIOR_IDLE_MS 175

#define U_LEFT_KEYS LT1 LT2 LT3 LT4 LT5 LM1 LM2 LM3 LM4 LM5 LB5 LB1 LB2 LB3 LB4  // left-hand keys
#define U_RIGHT_KEYS RT5 RT1 RT2 RT3 RT4 RM5 RM1 RM2 RM3 RM4 RB5 RB1 RB2 RB3 RB4  // right-hand keys
